pipeline:
  name: test18
  identifier: test18
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: FF
        identifier: FF
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 100
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: <+input>
            serviceDefinition:
              spec: {}
              type: Kubernetes
          infrastructure:
            environmentRef: <+input>
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: <+input>
                namespace: <+input>
                releaseName: release-<+INFRA_KEY_SHORT_ID>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
