pipeline:
  name: test18
  identifier: test18
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: FF
        identifier: FF
        description: ""
        type: FeatureFlag
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
